### ISSUE TITLE
[Epic] vinyl-fs 2.0

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#92]
Figured I'd create a 2.0 milestone epic to track what still needs to be done.

- [x] Remove the `watch` method from library and vinyl-adapter spec
- [ ] Update vinyl blog post
- [ ] More testing on sourcemap integration
- [x] Decide on resolution for #83 
- [ ] Wrap up/decide on any outstanding issues that we can actually control
- [x] Update to test on Node 4.0 (remove iojs support)

@contra anything else?

**Comment by contra** [comment]
@phated nope thats it for going to 2.0, thanks for the post

**Comment by iliakan** [comment]
What's the point of integrating sourcemaps into src/dest? It looks like a completely artificial merging in of a standalone plugin. 

Let them stay apart as they should and as they actually do.

**Comment by phated** [comment]
Already done. No point in discussing.

**Comment by contra** [comment]
@iliakan Reduction of boilerplate, might have been better to do in gulp instead of vinyl-fs - still time to change it

**Comment by iliakan** [comment]
Gulp actively encourages splitting concerns. Here is no benefit of merging them. 
Separate sourcemaps are as concise as an option, but more verbose and configurable.

**Comment by phated** [comment]
I addressed that point in my Thunder Plains Conf talk. Gulp defers stuff to userland religiously but we realize when something is used in almost every task and can make the decision to bring it into core. Sourcemaps is the most notable case. We still depend on the userland module so we get all fixes and features.

**Comment by phated** [comment]
Closing this due to pushing forward on vinyl-fs 3
